### ISSUE TITLE
Build Action fails

### ISSUE THREAD

**Issue by SvenCSchmidt** [MangoIV/draculady-config#10]
Just forked the repo and tried to build (also tried to build the fork directly). I get the following error at Build (west build).

Run west build -s zmk/app -b le_chiff_ble -- \
  
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /__w/zmk-config-chiffre/zmk-config-chiffre/zmk/app
-- CMake version: 3.27.7
-- Found Python3: /usr/bin/python3 (found suitable version "3.[8](https://github.com/SvenCSchmidt/zmk-config-chiffre/actions/runs/9251456872/job/25447019788#step:9:8).10", minimum required is "3.[8](https://github.com/SvenCSchmidt/zmk-config-chiffre/actions/runs/9251456872/job/25447019788#step:9:9)") found components: Interpreter 
-- Cache files will be written to: /__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/.cache
-- Zephyr version: 3.5.0 (/__w/zmk-config-chiffre/zmk-config-chiffre/zephyr)
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Adding ZMK config directory as board root: /__w/zmk-config-chiffre/zmk-config-chiffre/zmk-config
-- ZMK Config directory: /__w/zmk-config-chiffre/zmk-config-chiffre/zmk-config
-- Using keymap file: /__w/zmk-config-chiffre/zmk-config-chiffre/zmk-config/boards/arm/le_chiff_ble/le_chiff_ble.keymap
-- Board: le_chiff_ble
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.3 (/opt/zephyr-sdk-0.16.3)
-- Found toolchain: zephyr 0.16.3 (/opt/zephyr-sdk-0.16.3)
-- Found Dtc: /opt/zephyr-sdk-0.16.3/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /__w/zmk-config-chiffre/zmk-config-chiffre/zmk-config/boards/arm/le_chiff_ble/le_chiff_ble.dts
-- Found devicetree overlay: /__w/zmk-config-chiffre/zmk-config-chiffre/zmk-config/boards/arm/le_chiff_ble/le_chiff_ble.keymap
devicetree error: 'pinctrl-0' is marked as required in 'properties:' in /__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/dts/bindings/i2c/nordic,nrf-twi.yaml, but does not appear in <Node /soc/i2c@40003000 in '/__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/misc/empty_file.c'>
-- In: /__w/zmk-config-chiffre/zmk-config-chiffre/build/zephyr, command: /usr/bin/python3;/__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/scripts/dts/gen_defines.py;--dts;/__w/zmk-config-chiffre/zmk-config-chiffre/build/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/__w/zmk-config-chiffre/zmk-config-chiffre/zmk/app/module/dts/bindings;/__w/zmk-config-chiffre/zmk-config-chiffre/zmk/app/dts/bindings;/__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/dts/bindings;--header-out;/__w/zmk-config-chiffre/zmk-config-chiffre/build/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/__w/zmk-config-chiffre/zmk-config-chiffre/build/zephyr/zephyr.dts.new;--edt-pickle-out;/__w/zmk-config-chiffre/zmk-config-chiffre/build/zephyr/edt.pickle;--vendor-prefixes;/__w/zmk-config-chiffre/zmk-config-chiffre/zmk/app/dts/bindings/vendor-prefixes.txt;--vendor-prefixes;/__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/cmake/modules/dts.cmake:27[9](https://github.com/SvenCSchmidt/zmk-config-chiffre/actions/runs/9251456872/job/25447019788#step:9:10) (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/cmake/modules/zephyr_default.cmake:[12](https://github.com/SvenCSchmidt/zmk-config-chiffre/actions/runs/9251456872/job/25447019788#step:9:13)9 (include)
  /__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /__w/zmk-config-chiffre/zmk-config-chiffre/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:8 (find_package)
-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/__w/zmk-config-chiffre/zmk-config-chiffre/build -GNinja -DBOARD=le_chiff_ble -DZMK_CONFIG=/__w/zmk-config-chiffre/zmk-config-chiffre/zmk-config -S/__w/zmk-config-chiffre/zmk-config-chiffre/zmk/app
Error: Process completed with exit code 1.

Any help appreciated.

**Comment by MangoIV** [comment]
Hi! I've tried to pin the version of this stuff such that it doesn't fail every time someone is trying to rerun this but apparently it doesn't work. I also can't immediately see the error. I think it would be best to refer to the zmk team to ask what has changed. Bonus points if you can report here later, sorry I can't help here :(

**Comment by SvenCSchmidt** [comment]
Short update: I have solved the build problem. I just have to test the FW on a board first, which will probably not be possible until tomorrow. After that I can post a short info here or try to create a PR.
Disclaimer: I am not a developer. I have only combined and adapted based on information. Accordingly, I cannot say anything about the quality of my solution.
For the impatient, you can check out the latest commit in my fork.

**Comment by MangoIV** [comment]
@SvenCSchmidt perhaps also try to rebase on current HEAD, maybe that already fixes the issues.

**Comment by SvenCSchmidt** [comment]
Solved with your last commits. Thank you
