### ISSUE TITLE
Default map fails build

### ISSUE THREAD

**Issue by ghidalgo93** [MangoIV/draculady-config#2]
I forked over this repo and followed the steps to build, the default build is failing for me and not producing any firmware. The last commit I see was ~5mo ago, any ideas what might be going on?

Steps to reproduce:
1) Folk this repo (https://github.com/MangoIV/le_chiff_ble_config)
2) Clone locally
3) Add a comment to .keymap file in order to get it to rebuild & confirm gh actions for a forked repo
![image](https://user-images.githubusercontent.com/25713142/169658318-260ddc08-9db8-44fd-aaf0-f4561ad46168.png)

**Comment by MangoIV** [comment]
This happens if your build env is not deterministic, the relevant error is: 
> CMake 3.20.0 or higher is required.  You are running version 3.16.3

**Comment by MangoIV** [comment]
You want to modify the `build.yml`. I do not have the time to do that currently, but it shouldn't be hard to adjust to a more recent version of `zmk` and `cmake`. There should be more recent examples of (compiling) zmk firmwars with GH workflows to be found on my GH profile, feel free to have a look at those.

**Comment by MangoIV** [comment]
Fixed it.
